# Created by: Johannes Lundberg <johalun0@gmail.com>
# $FreeBSD$

PORTNAME=	libepoll-shim
PORTVERSION=	0.0.20191109
CATEGORIES=	devel

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Small library that implements epoll on top of kqueue

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	jiixyj
GH_PROJECT=	epoll-shim
GH_TAGNAME=	b99d614abf0c58b43bc5cf796c38780aeb71d5b0

USE_LDCONFIG=	yes

.include <bsd.port.mk>
